name: Sort en.xml

on:
  workflow_dispatch:

jobs:
  sort-en-xml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install lxml
        run: pip install lxml

      - name: Sort en.xml
        run: python .github/scripts/sort_en_xml.py

      - name: Commit sorted file
        run: |
          if git diff --name-only | grep -q 'languages/en.xml'; then
            git config user.name "github-actions"
            git config user.email "actions@users.noreply.github.com"
            git add languages/en.xml
            git commit -m "chore: sort en.xml alphabetically"
            git push
          else
            echo "No changes to commit."
          fi