name: Sort en.xml

on:
  workflow_dispatch:

jobs:
  sort-en-xml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Sort en.xml
        run: python scripts/sort_en_xml.py

      - name: Commit sorted file
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add adm_program/languages/en.xml
          if ! git diff --quiet; then
            git commit -m "chore: sort en.xml alphabetically"
            git push
          fi
