name: Sort en.xml

on:
  workflow_dispatch:

jobs:
  sort-en-xml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install lxml
        run: pip install lxml

      - name: Run sort script
        run: python .github/scripts/sort_en_xml.py

      - name: Commit and push changes
        env:
          WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"

          if git diff --quiet; then
            echo "No changes detected."
          else
            git add languages/en.xml
            git commit -m "chore: sort en.xml alphabetically"
            git push https://x-access-token:${WORKFLOW_TOKEN}@github.com/${{ github.repository }}.git HEAD:$(echo "${{ github.ref }}" | sed 's|refs/heads/||')
          fi
