name: Sort en.xml

on:
  workflow_dispatch:

jobs:
  sort-en-xml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install lxml
        run: pip install lxml

      - name: Sort en.xml
        run: python .github/scripts/sort_en_xml.py

      - name: Commit sorted file
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add languages/en.xml
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: alphabetically sort en.xml"
            git push https://x-access-token:${{ secrets.WORKFLOW_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
          fi